services:
  - type: static
    name: resumexpert-ai
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://resumexpert-ai-backend.onrender.com/api
      - key: NODE_ENV
        value: production